In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('dataset.csv')
data.head()

,"group (control:0, AMI:1)","sub-type for AMI( STEMI:0, NON-STEMI :1, control:2)",Age,"Gender (0:female, 1:male)",WBC,RBC,HGB,BA,EO,LY,...,MPV,PLT,HCT,MCV,RDW-SD,RDW-CV,MCH,MCHC,PDW,PCT
0,0,2,28.0,1,10.90,5.09,15.3,0.06,0.19,2.77,...,10.00,309.0,46.3,91.9,58.0,11.5,30.1,33.0,11.2,0.31
1,0,2,40.0,0,5.96,5.16,15.6,0.03,0.37,2.36,...,13.30,214.0,45.9,89.0,40.4,12.4,30.2,34.0,22.0,0.28
2,0,2,64.0,1,4.59,5.51,14.9,0.05,0.05,1.12,...,11.00,193.0,43.8,79.5,38.2,13.4,27.0,34.0,13.6,0.21
3,0,2,57.0,0,7.26,4.70,12.5,0.05,0.11,3.46,...,10.00,321.0,40.2,85.5,46.0,14.8,24.6,32.1,11.9,0.32
4,0,2,58.0,0,7.15,4.37,12.1,0.03,0.34,1.90,...,9.69,209.0,38.0,87.0,48.0,15.1,37.7,31.8,11.4,0.20

ubah nama kolomnya

In [3]:
data = data.rename(columns={'sub-type for AMI( STEMI:0, NON-STEMI :1, control:2)': 'sub-type for AMI'})
data = data.rename(columns={'Gender (0:female, 1:male)':'Gender'})
data

,"group (control:0, AMI:1)",sub-type for AMI,Age,Gender,WBC,RBC,HGB,BA,EO,LY,...,MPV,PLT,HCT,MCV,RDW-SD,RDW-CV,MCH,MCHC,PDW,PCT
0,0,2,28.0,1,10.90,5.09,15.3,0.06,0.19,2.77,...,10.00,309.0,46.30,91.9,58.0,11.5,30.1,33.00,11.2,0.31
1,0,2,40.0,0,5.96,5.16,15.6,0.03,0.37,2.36,...,13.30,214.0,45.90,89.0,40.4,12.4,30.2,34.00,22.0,0.28
2,0,2,64.0,1,4.59,5.51,14.9,0.05,0.05,1.12,...,11.00,193.0,43.80,79.5,38.2,13.4,27.0,34.00,13.6,0.21
3,0,2,57.0,0,7.26,4.70,12.5,0.05,0.11,3.46,...,10.00,321.0,40.20,85.5,46.0,14.8,24.6,32.10,11.9,0.32
4,0,2,58.0,0,7.15,4.37,12.1,0.03,0.34,1.90,...,9.69,209.0,38.00,87.0,48.0,15.1,37.7,31.80,11.4,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,1,1,43.0,1,10.09,5.25,15.6,0.03,0.11,3.03,...,8.50,259.0,43.20,82.3,41.0,13.8,29.7,36.10,15.8,0.22
977,1,1,58.0,1,14.32,5.34,15.0,0.11,0.31,3.33,...,10.10,227.0,43.60,86.0,38.2,13.1,28.1,34.40,11.6,0.23
978,1,0,62.0,1,9.64,4.26,13.9,0.05,0.01,0.83,...,10.90,171.0,39.50,92.5,43.5,12.8,32.6,35.20,13.4,0.19
979,1,1,48.0,0,11.49,4.05,12.6,0.12,0.06,3.55,...,9.60,309.0,37.79,93.1,40.4,12.0,31.0,33.29,10.1,0.30
980,1,1,58.0,0,7.30,4.07,12.1,0.03,0.07,2.25,...,9.40,182.0,34.40,84.5,41.1,13.3,29.7,35.20,10.3,0.17

In [4]:
data = data[['sub-type for AMI', 'Age', 'Gender','WBC',
       'RBC', 'HGB', 'BA', 'EO', 'LY', 'MO', 'NEU', 'NEU/LY', 'PLT/LY',
       'MPV/LY', 'LY/MO', 'MPV', 'PLT', 'HCT', 'MCV', 'RDW-SD', 'RDW-CV',
       'MCH', 'MCHC', 'PDW ', 'PCT']].copy()
data

,sub-type for AMI,Age,Gender,WBC,RBC,HGB,BA,EO,LY,MO,...,MPV,PLT,HCT,MCV,RDW-SD,RDW-CV,MCH,MCHC,PDW,PCT
0,2,28.0,1,10.90,5.09,15.3,0.06,0.19,2.77,0.96,...,10.00,309.0,46.30,91.9,58.0,11.5,30.1,33.00,11.2,0.31
1,2,40.0,0,5.96,5.16,15.6,0.03,0.37,2.36,0.43,...,13.30,214.0,45.90,89.0,40.4,12.4,30.2,34.00,22.0,0.28
2,2,64.0,1,4.59,5.51,14.9,0.05,0.05,1.12,0.27,...,11.00,193.0,43.80,79.5,38.2,13.4,27.0,34.00,13.6,0.21
3,2,57.0,0,7.26,4.70,12.5,0.05,0.11,3.46,0.70,...,10.00,321.0,40.20,85.5,46.0,14.8,24.6,32.10,11.9,0.32
4,2,58.0,0,7.15,4.37,12.1,0.03,0.34,1.90,0.47,...,9.69,209.0,38.00,87.0,48.0,15.1,37.7,31.80,11.4,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,1,43.0,1,10.09,5.25,15.6,0.03,0.11,3.03,0.52,...,8.50,259.0,43.20,82.3,41.0,13.8,29.7,36.10,15.8,0.22
977,1,58.0,1,14.32,5.34,15.0,0.11,0.31,3.33,1.45,...,10.10,227.0,43.60,86.0,38.2,13.1,28.1,34.40,11.6,0.23
978,0,62.0,1,9.64,4.26,13.9,0.05,0.01,0.83,0.39,...,10.90,171.0,39.50,92.5,43.5,12.8,32.6,35.20,13.4,0.19
979,1,48.0,0,11.49,4.05,12.6,0.12,0.06,3.55,0.63,...,9.60,309.0,37.79,93.1,40.4,12.0,31.0,33.29,10.1,0.30
980,1,58.0,0,7.30,4.07,12.1,0.03,0.07,2.25,0.57,...,9.40,182.0,34.40,84.5,41.1,13.3,29.7,35.20,10.3,0.17

cek ada tidaknya NULL value

In [5]:
print(data.isnull().sum())

sub-type for AMI    0
Age                 0
Gender              0
WBC                 0
RBC                 0
HGB                 0
BA                  0
EO                  0
LY                  0
MO                  0
NEU                 0
NEU/LY              0
PLT/LY              0
MPV/LY              0
LY/MO               0
MPV                 0
PLT                 0
HCT                 0
MCV                 0
RDW-SD              0
RDW-CV              0
MCH                 0
MCHC                0
PDW                 0
PCT                 0
dtype: int64

In [6]:
#statistik deskriptif dari dataset
data.describe()

,sub-type for AMI,Age,Gender,WBC,RBC,HGB,BA,EO,LY,MO,...,MPV,PLT,HCT,MCV,RDW-SD,RDW-CV,MCH,MCHC,PDW,PCT
count,981.000000,981.000000,981.000000,981.000000,981.000000,981.000000,981.000000,981.000000,981.000000,981.000000,...,981.000000,981.000000,981.000000,981.000000,981.000000,981.000000,981.000000,981.000000,981.000000,981.000000
mean,1.328236,59.166157,0.579001,9.091019,4.755474,13.747441,0.056177,0.163639,2.490805,0.659949,...,9.817655,259.752294,41.048981,86.699021,41.864730,13.670275,29.004944,33.433721,13.499235,0.254485
std,0.769513,10.851216,0.493971,3.201733,0.546632,1.576756,0.062927,0.141448,1.175224,0.260870,...,3.450854,71.165335,4.357617,5.635603,4.041242,1.370960,2.390958,1.545107,2.927959,0.135490
min,0.000000,20.000000,0.000000,3.000000,2.700000,10.080000,0.010000,0.010000,0.400000,0.040000,...,6.100000,100.000000,19.400000,61.300000,18.100000,9.600000,18.100000,23.600000,7.600000,0.050000
25%,1.000000,51.000000,0.000000,6.980000,4.380000,12.600000,0.020000,0.080000,1.800000,0.490000,...,8.900000,210.000000,38.000000,83.900000,39.000000,12.800000,27.900000,32.500000,11.100000,0.200000
50%,2.000000,60.000000,1.000000,8.500000,4.750000,13.700000,0.050000,0.120000,2.290000,0.600000,...,9.800000,256.000000,41.100000,86.800000,41.000000,13.400000,29.200000,33.500000,12.800000,0.240000
75%,2.000000,67.000000,1.000000,10.520000,5.140000,14.900000,0.080000,0.210000,2.920000,0.780000,...,10.500000,298.000000,44.200000,89.800000,43.800000,14.200000,30.400000,34.400000,16.390000,0.280000
max,2.000000,82.000000,1.000000,30.900000,7.220000,17.890000,1.100000,1.150000,9.000000,1.900000,...,110.400000,754.000000,54.000000,120.000000,68.400000,22.300000,44.100000,55.290000,23.100000,2.890000

In [7]:
data.dtypes

sub-type for AMI      int64
Age                 float64
Gender                int64
WBC                 float64
RBC                 float64
HGB                 float64
BA                  float64
EO                  float64
LY                  float64
MO                  float64
NEU                 float64
NEU/LY              float64
PLT/LY              float64
MPV/LY              float64
LY/MO               float64
MPV                 float64
PLT                 float64
HCT                 float64
MCV                 float64
RDW-SD              float64
RDW-CV              float64
MCH                 float64
MCHC                float64
PDW                 float64
PCT                 float64
dtype: object

In [8]:
data.shape

(981, 25)

In [9]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

melakukan pengujian pada distribusi data menggunakan shapiro-wilk

In [10]:
from scipy import stats
#fungsi untuk melakukan uji shapiro-wilk pada semua kolom
def shapiro_wilk_test(data):
    results = {}
    for column in data.columns:
        stat, p_value = stats.shapiro(data[column].dropna())  # dropna() untuk menghindari null values
        results[column] = {'statistic': stat, 'p_value': p_value}
    return results

#menjalankan uji dan menampilkan hasilnya
shapiro_results = shapiro_wilk_test(data)
#menampilkan hasil uji untuk setiap kolom
for column, result in shapiro_results.items():
    print(f"Uji Shapiro-Wilk untuk {column}: Statistik = {result['statistic']}, P-value = {result['p_value']}")
    if result['p_value'] > 0.05:
        print(f"{column}: Data terdistribusi normal (gagal menolak hipotesis nol)\n")
    else:
        print(f"{column}: Data tidak terdistribusi normal (menolak hipotesis nol)\n")

Uji Shapiro-Wilk untuk sub-type for AMI: Statistik = 0.7499774098396301, P-value = 4.851721995690485e-36
sub-type for AMI: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk Age: Statistik = 0.9893985986709595, P-value = 1.5934265320538543e-06
Age: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk Gender: Statistik = 0.6274404525756836, P-value = 1.2384675827702733e-41
Gender: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk WBC: Statistik = 0.9069954752922058, P-value = 5.5064869600055865e-24
WBC: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk RBC: Statistik = 0.996276319026947, P-value = 0.019254593178629875
RBC: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk HGB: Statistik = 0.9918331503868103, P-value = 3.0001589038874954e-05
HGB: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk BA: Statistik = 0.4791054129600525, P-value = 0.0
BA: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk EO: Statistik = 0.8256726264953613, P-value = 2.4038109508919955e-31
EO: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk LY: Statistik = 0.8764835596084595, P-value = 3.516579752173953e-27
LY: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk MO: Statistik = 0.9240103960037231, P-value = 7.703283032597377e-22
MO: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk NEU: Statistik = 0.8336166143417358, P-value = 9.184467441788243e-31
NEU: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk NEU/LY: Statistik = 0.5678697824478149, P-value = 7.987401246651457e-44
NEU/LY: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk PLT/LY: Statistik = 0.7670153975486755, P-value = 4.283789261279686e-35
PLT/LY: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk MPV/LY: Statistik = 0.588131308555603, P-value = 4.175869423687955e-43
MPV/LY: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk LY/MO: Statistik = 0.781415581703186, P-value = 2.9893696074511676e-34
LY/MO: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk MPV: Statistik = 0.20916426181793213, P-value = 0.0
MPV: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk PLT: Statistik = 0.9607710838317871, P-value = 1.4392633491396934e-15
PLT: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk HCT: Statistik = 0.9953740835189819, P-value = 0.004576458130031824
HCT: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk MCV: Statistik = 0.9409393072128296, P-value = 2.5863438118119617e-19
MCV: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk RDW-SD: Statistik = 0.8845739364624023, P-value = 2.1291710203024876e-26
RDW-SD: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk RDW-CV: Statistik = 0.8720953464508057, P-value = 1.3752066175228114e-27
RDW-CV: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk MCH: Statistik = 0.9425042271614075, P-value = 4.698843930565398e-19
MCH: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk MCHC: Statistik = 0.8508317470550537, P-value = 2.0129377416701288e-29
MCHC: Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk PDW : Statistik = 0.9423559904098511, P-value = 4.438270146889889e-19
PDW : Data tidak terdistribusi normal (menolak hipotesis nol)

Uji Shapiro-Wilk untuk PCT: Statistik = 0.3697202801704407, P-value = 0.0
PCT: Data tidak terdistribusi normal (menolak hipotesis nol)

feature selection: filter method

In [11]:
from scipy.stats import spearmanr

# Memisahkan fitur X dan target y
X = data.drop(columns=['sub-type for AMI'])
y = data['sub-type for AMI']

# Menghitung korelasi Spearman
spearman = {}
for kolom in X.columns:
    # Mengambil korelasi Spearman antara fitur dan target
    correlation, _ = spearmanr(X[kolom], y)  # Hanya mengambil korelasi, bukan p-value
    spearman[kolom] = correlation

# Menyortir fitur berdasarkan nilai korelasi dengan abs()
fitur_tersortir = sorted(spearman.items(), key=lambda x: abs(x[1]), reverse=True)

# Menampilkan fitur dan nilai korelasi
for feature, corr in fitur_tersortir:
    print(f"{feature}: {corr}")

WBC: -0.6039680651943417
NEU: -0.558550490224538
MO: -0.326899290598384
PDW : -0.3235464902809049
MPV: 0.2695681366989625
NEU/LY: -0.26157990493218747
MCHC: -0.233208499501585
RDW-CV: -0.20548534778728095
BA: -0.2037543637948184
MPV/LY: 0.18771740222898722
Gender: -0.1735842917562152
PLT/LY: 0.12912836957815513
LY/MO: 0.12717903739758057
LY: -0.11119197234908462
PCT: 0.10577645519735131
MCH: -0.08926470044455803
HGB: -0.08823815675305229
EO: 0.08180636498642022
Age: -0.07057554882350114
MCV: 0.05227060170491408
RDW-SD: -0.04210842203099182
RBC: -0.04127932818704308
PLT: -0.02483347426181484
HCT: -0.004246851208031298

In [12]:
#menghapus fitur dengan korelasi rendah
fitur_terpilih = {k: v for k, v in spearman.items() if abs(v) >= 0.3}
print("fitur terpilih: ",fitur_terpilih)

fitur terpilih:  {'WBC': -0.6039680651943417, 'MO': -0.326899290598384, 'NEU': -0.558550490224538, 'PDW ': -0.3235464902809049}

In [13]:
data = data[['sub-type for AMI','WBC','MO','NEU','PDW ']].copy()
data

     sub-type for AMI    WBC    MO   NEU  PDW
0                   2  10.90  0.96  6.22  11.2
1                   2   5.96  0.43  2.77  22.0
2                   2   4.59  0.27  3.10  13.6
3                   2   7.26  0.70  2.94  11.9
4                   2   7.15  0.47  4.41  11.4
..                ...    ...   ...   ...   ...
976                 1  10.09  0.52  6.40  15.8
977                 1  14.32  1.45  9.11  11.6
978                 0   9.64  0.39  8.36  13.4
979                 1  11.49  0.63  7.30  10.1
980                 1   7.30  0.57  4.37  10.3

[981 rows x 5 columns]

mengecek apakah label balance atau tidak

In [14]:
#menghitung jumlah sample per kelas
print(data['sub-type for AMI'].value_counts())

sub-type for AMI
2    504
1    295
0    182
Name: count, dtype: int64

kelas 2 = 51.3%

kelas 1 = 30.1%

kelas 0 = 18.5%

sehingga dapat dikatakan data tidak seimbang atau imbalance

In [15]:
X = data.iloc[:,:5]
X.head()

   sub-type for AMI    WBC    MO   NEU  PDW
0                 2  10.90  0.96  6.22  11.2
1                 2   5.96  0.43  2.77  22.0
2                 2   4.59  0.27  3.10  13.6
3                 2   7.26  0.70  2.94  11.9
4                 2   7.15  0.47  4.41  11.4

In [16]:
Y = data.loc[:,['sub-type for AMI']]
Y.head()

   sub-type for AMI
0                 2
1                 2
2                 2
3                 2
4                 2

membagi dataset menjadi traning set dan test set

In [17]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn import datasets

#pisahkan data menjadi traning dan testing
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=42,stratify=Y)

balancing = SMOTE(random_state=42)
X_train_smote,y_train_smote = balancing.fit_resample(X_train,y_train)

In [18]:
len(y_train)

686

# Implementasi model 1: Logistic regression

In [19]:
# multiclass logistic regression 
from sklearn.linear_model import LogisticRegression

#membentuk model regresi logistik untuk multiclass
model = LogisticRegression(multi_class='multinomial',solver='lbfgs')

model.fit(X_train,y_train)

print(model.coef_)

[[-6.14818638e+00  2.79104417e-01  2.15754080e-01 -3.54464974e-02
   1.46708969e-01]
 [-4.27143028e-01 -3.08033524e-02 -8.15729087e-02  9.17508839e-02
   1.74767396e-03]
 [ 6.57532940e+00 -2.48301065e-01 -1.34181171e-01 -5.63043865e-02
  -1.48456643e-01]]

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [21]:
#melakukan prediksi terhadap label
predict = model.predict(X_test)
print(predict)

#untuk  mendapatkan probabilitas prediksi untuk setiap kelas
probabilitas = model.predict_proba(X_test)
print(probabilitas)

[2 2 1 1 0 1 2 2 1 1 2 1 0 1 0 0 2 2 1 2 1 0 0 2 0 1 0 1 2 2 2 2 2 1 2 1 1
 0 2 2 0 2 2 0 0 1 1 1 1 2 2 2 0 1 1 1 2 2 2 1 1 0 2 1 1 0 1 0 2 1 2 1 2 2
 2 2 0 2 2 1 0 2 2 2 2 2 2 2 0 1 0 2 1 1 0 1 1 2 1 2 0 0 2 1 2 2 2 1 1 2 0
 0 2 2 0 2 1 2 1 2 2 0 2 2 1 0 2 2 2 1 2 1 1 2 2 1 2 2 2 1 2 2 1 0 2 2 1 1
 1 0 1 1 1 2 1 2 1 2 2 1 1 2 2 2 0 1 2 2 2 2 2 1 0 1 2 2 1 1 2 0 2 2 2 1 2
 1 2 0 0 0 2 1 1 1 2 2 2 2 2 1 2 1 2 1 1 2 2 2 0 2 1 0 2 2 2 2 0 2 2 1 2 2
 2 2 2 2 1 2 0 2 2 2 0 0 1 2 2 2 1 1 2 2 2 2 0 0 0 0 2 1 2 2 2 0 2 1 2 2 2
 2 0 1 2 2 0 2 1 2 1 1 2 2 0 1 0 2 0 1 1 1 0 0 0 2 2 2 2 2 2 2 2 2 1 0 2]
[[2.80499743e-06 3.12432303e-02 9.68753965e-01]
 [6.10911638e-07 1.32965048e-02 9.86702884e-01]
 [3.66839826e-02 9.42702324e-01 2.06136936e-02]
 [6.07616111e-02 9.30058963e-01 9.17942548e-03]
 [9.71298010e-01 2.87018187e-02 1.71477431e-07]
 [2.19788554e-02 9.51802669e-01 2.62184759e-02]
 [7.35659960e-07 1.44680082e-02 9.85531256e-01]
 [3.50434486e-07 1.35601179e-02 9.86439532e-01]
 [2.70873121e-02 9.50031923e-01 2.28807651e-02]
 [4.83418604e-02 9.46905377e-01 4.75276310e-03]
 [1.67793710e-06 2.64105476e-02 9.73587774e-01]
 [1.17233958e-02 9.34188305e-01 5.40882997e-02]
 [9.71890543e-01 2.81093570e-02 9.99487076e-08]
 [3.12015217e-02 9.45015938e-01 2.37825406e-02]
 [8.39708461e-01 1.60288886e-01 2.65278419e-06]
 [9.47308803e-01 5.26907128e-02 4.83936503e-07]
 [2.47876144e-06 2.37920566e-02 9.76205465e-01]
 [1.36996533e-07 6.52489115e-03 9.93474972e-01]
 [7.38835209e-03 8.96903235e-01 9.57084133e-02]
 [6.99202864e-07 1.42513802e-02 9.85747921e-01]
 [6.20319497e-02 9.34435298e-01 3.53275232e-03]
 [9.46167625e-01 5.38312379e-02 1.13721926e-06]
 [9.47498126e-01 5.25015038e-02 3.70024505e-07]
 [5.06798523e-07 1.07193862e-02 9.89280107e-01]
 [9.66485513e-01 3.35142675e-02 2.19212252e-07]
 [3.12015217e-02 9.45015938e-01 2.37825406e-02]
 [6.53614517e-01 3.46383881e-01 1.60173231e-06]
 [3.54069248e-02 9.50082426e-01 1.45106494e-02]
 [2.06191938e-06 2.75479494e-02 9.72449989e-01]
 [8.75831849e-07 1.60806097e-02 9.83918514e-01]
 [1.04979016e-06 1.85078813e-02 9.81491069e-01]
 [3.77158978e-07 1.09045640e-02 9.89095059e-01]
 [2.79367450e-07 1.09487054e-02 9.89051015e-01]
 [3.74679337e-02 9.52558416e-01 9.97364980e-03]
 [6.96311058e-07 1.48400069e-02 9.85159297e-01]
 [1.12071327e-02 9.37121898e-01 5.16709698e-02]
 [3.31048593e-03 8.06618773e-01 1.90070741e-01]
 [9.34711258e-01 6.52877743e-02 9.67655926e-07]
 [1.88465784e-07 7.89666294e-03 9.92103149e-01]
 [7.73813713e-07 1.65676243e-02 9.83431602e-01]
 [9.42313984e-01 5.76852743e-02 7.41794156e-07]
 [1.56519567e-06 2.51815437e-02 9.74816891e-01]
 [7.52061890e-08 5.87874859e-03 9.94121176e-01]
 [8.89792063e-01 1.10205719e-01 2.21838443e-06]
 [9.14342645e-01 8.56554047e-02 1.94995588e-06]
 [1.79637285e-02 9.62152846e-01 1.98834258e-02]
 [2.06222299e-02 9.45104473e-01 3.42732967e-02]
 [1.61010084e-02 9.64624907e-01 1.92740850e-02]
 [2.68960413e-02 9.45415741e-01 2.76882181e-02]
 [4.93037688e-06 4.28392289e-02 9.57155841e-01]
 [4.91514747e-07 1.16952896e-02 9.88304219e-01]
 [2.52413147e-07 8.54893887e-03 9.91450809e-01]
 [9.81555351e-01 1.84446094e-02 3.94914064e-08]
 [1.40421562e-02 9.48099056e-01 3.78587879e-02]
 [2.78739733e-02 9.42924161e-01 2.92018658e-02]
 [6.67553893e-02 9.27487892e-01 5.75671894e-03]
 [7.39717304e-07 1.39396071e-02 9.86059653e-01]
 [7.55222034e-06 6.43462740e-02 9.35646174e-01]
 [5.26245864e-07 1.19925027e-02 9.88006971e-01]
 [2.22377489e-02 9.54194014e-01 2.35682375e-02]
 [9.83818469e-03 8.97050616e-01 9.31111996e-02]
 [9.40866128e-01 5.91333239e-02 5.48568695e-07]
 [9.94912157e-07 2.14469264e-02 9.78552079e-01]
 [5.58194791e-02 9.33653780e-01 1.05267412e-02]
 [3.52429847e-02 9.36872094e-01 2.78849212e-02]
 [8.56946696e-01 1.43051110e-01 2.19331419e-06]
 [2.88690783e-02 9.46908990e-01 2.42219319e-02]
 [9.67840459e-01 3.21592620e-02 2.78947812e-07]
 [1.72870101e-07 7.33109147e-03 9.92668736e-01]
 [3.01325256e-02 9.45625133e-01 2.42423416e-02]
 [4.83105639e-06 3.64899543e-02 9.63505215e-01]
 [1.19902251e-02 9.31066607e-01 5.69431680e-02]
 [2.06191938e-06 2.75479494e-02 9.72449989e-01]
 [9.11038565e-06 5.66325151e-02 9.43358375e-01]
 [3.16401595e-07 1.08626098e-02 9.89137074e-01]
 [1.39060799e-06 2.02198774e-02 9.79778732e-01]
 [9.43551635e-01 5.64480306e-02 3.34607140e-07]
 [1.31468944e-06 2.11801915e-02 9.78818494e-01]
 [3.14900081e-06 3.30196399e-02 9.66977211e-01]
 [4.48251105e-02 9.46233262e-01 8.94162748e-03]
 [9.77280737e-01 2.27192443e-02 1.81970564e-08]
 [1.76199687e-07 6.73676767e-03 9.93263056e-01]
 [2.03737062e-06 3.00091621e-02 9.69988801e-01]
 [6.18580948e-07 1.41425614e-02 9.85856820e-01]
 [3.65027082e-07 1.09836040e-02 9.89016031e-01]
 [1.74626164e-06 3.44037313e-02 9.65594522e-01]
 [4.61241342e-07 1.08835859e-02 9.89115953e-01]
 [1.00124010e-06 1.83150439e-02 9.81683955e-01]
 [9.33976389e-01 6.60228493e-02 7.62106726e-07]
 [3.79277054e-02 9.47251857e-01 1.48204377e-02]
 [8.86293638e-01 1.13704961e-01 1.40096607e-06]
 [3.17361314e-07 1.07399282e-02 9.89259754e-01]
 [3.03017165e-02 9.52301832e-01 1.73964519e-02]
 [7.11249256e-03 9.02780005e-01 9.01075020e-02]
 [9.37181385e-01 6.28176693e-02 9.46129402e-07]
 [7.68083447e-02 9.11685253e-01 1.15064022e-02]
 [2.90753507e-02 9.66187888e-01 4.73676159e-03]
 [2.02966212e-06 2.42645827e-02 9.75733388e-01]
 [8.65847993e-03 9.10894654e-01 8.04468661e-02]
 [1.06173121e-06 1.94178097e-02 9.80581129e-01]
 [8.97725855e-01 1.02271820e-01 2.32437313e-06]
 [8.87981549e-01 1.12017541e-01 9.09533143e-07]
 [4.59373338e-07 1.18277179e-02 9.88171823e-01]
 [1.17195653e-01 8.79184897e-01 3.61944936e-03]
 [2.58913026e-06 3.37860818e-02 9.66211329e-01]
 [3.34017839e-06 4.74962257e-02 9.52500434e-01]
 [4.75252233e-07 1.28088039e-02 9.87190721e-01]
 [2.62650174e-02 9.53852816e-01 1.98821670e-02]
 [1.87867088e-02 9.40777168e-01 4.04361229e-02]
 [2.57727240e-07 9.54322663e-03 9.90456516e-01]
 [6.13561859e-01 3.86406493e-01 3.16486508e-05]
 [9.42944632e-01 5.70550669e-02 3.01556751e-07]
 [1.57632826e-07 7.25437690e-03 9.92745465e-01]
 [5.66065257e-07 1.54119992e-02 9.84587435e-01]
 [9.41748160e-01 5.82514467e-02 3.93653489e-07]
 [2.16307383e-07 7.55473230e-03 9.92445051e-01]
 [2.84609420e-02 9.44419978e-01 2.71190803e-02]
 [4.87227303e-06 5.52480736e-02 9.44747054e-01]
 [6.51907298e-02 9.28041996e-01 6.76727439e-03]
 [2.96389385e-07 9.28693901e-03 9.90712765e-01]
 [2.90204261e-06 2.93065394e-02 9.70690559e-01]
 [9.47498126e-01 5.25015038e-02 3.70024505e-07]
 [3.87707289e-06 3.82514836e-02 9.61744639e-01]
 [5.83276632e-07 1.45142087e-02 9.85485208e-01]
 [2.09906094e-02 9.50283067e-01 2.87263239e-02]
 [9.33794630e-01 6.62051646e-02 2.04910121e-07]
 [6.22299550e-07 1.49986257e-02 9.85000752e-01]
 [5.56384134e-06 4.27747696e-02 9.57219667e-01]
 [4.15299050e-06 3.24549624e-02 9.67540885e-01]
 [1.52629384e-02 9.35935277e-01 4.88017842e-02]
 [4.56145217e-07 1.21669468e-02 9.87832597e-01]
 [1.61476801e-02 9.47174191e-01 3.66781285e-02]
 [2.44220992e-02 9.40651003e-01 3.49268982e-02]
 [9.97088302e-07 2.06011328e-02 9.79397870e-01]
 [3.74624901e-07 9.75532347e-03 9.90244302e-01]
 [1.10625137e-01 8.83921663e-01 5.45320001e-03]
 [2.12735594e-07 7.18687903e-03 9.92812908e-01]
 [3.00770856e-07 1.23184007e-02 9.87681299e-01]
 [3.15240123e-07 1.13180093e-02 9.88681675e-01]
 [8.77939991e-02 9.08329686e-01 3.87631474e-03]
 [9.72467782e-07 1.71881274e-02 9.82810900e-01]
 [2.01737786e-07 7.57217637e-03 9.92427622e-01]
 [1.98495706e-01 7.99858468e-01 1.64582601e-03]
 [9.96630512e-01 3.36948797e-03 4.18254601e-10]
 [3.53308797e-06 3.25648725e-02 9.67431594e-01]
 [2.30039090e-06 2.66186301e-02 9.73379069e-01]
 [3.16197554e-02 9.43541711e-01 2.48385334e-02]
 [4.79755722e-02 9.40638844e-01 1.13855834e-02]
 [3.55109184e-02 9.43403404e-01 2.10856775e-02]
 [9.43551635e-01 5.64480306e-02 3.34607140e-07]
 [4.81630528e-02 9.42340165e-01 9.49678220e-03]
 [3.66839826e-02 9.42702324e-01 2.06136936e-02]
 [7.34582935e-02 9.22544088e-01 3.99761877e-03]
 [3.20732778e-07 9.26345713e-03 9.90736222e-01]
 [1.65141806e-02 9.66188351e-01 1.72974683e-02]
 [1.91994802e-06 3.18361632e-02 9.68161917e-01]
 [7.14485174e-02 9.19325804e-01 9.22567836e-03]
 [1.10036161e-06 1.71098639e-02 9.82889036e-01]
 [1.64282729e-07 7.47084344e-03 9.92528992e-01]
 [3.28405406e-02 9.42516069e-01 2.46433903e-02]
 [1.94975601e-02 9.66402879e-01 1.40995605e-02]
 [1.87100952e-06 2.29286615e-02 9.77069467e-01]
 [3.59037771e-07 1.16178039e-02 9.88381837e-01]
 [4.29933089e-07 1.09692419e-02 9.89030328e-01]
 [9.69311359e-01 3.06885986e-02 4.18955081e-08]
 [1.42624006e-02 9.59783028e-01 2.59545718e-02]
 [2.51240128e-07 8.48370302e-03 9.91516046e-01]
 [1.28804205e-06 1.97192043e-02 9.80279508e-01]
 [2.04105985e-06 2.76218572e-02 9.72376102e-01]
 [1.62752620e-06 2.20962575e-02 9.77902115e-01]
 [3.90290040e-07 1.10439843e-02 9.88955625e-01]
 [2.69243589e-02 9.52337370e-01 2.07382713e-02]
 [9.16308526e-01 8.36904614e-02 1.01304788e-06]
 [1.66076578e-02 9.43803716e-01 3.95886262e-02]
 [4.29750467e-06 4.20446026e-02 9.57951100e-01]
 [1.87295529e-06 2.47414099e-02 9.75256717e-01]
 [2.62689078e-02 9.56252288e-01 1.74788046e-02]
 [2.25290239e-02 9.57598450e-01 1.98725259e-02]
 [3.52137628e-07 1.02646380e-02 9.89735010e-01]
 [9.38559335e-01 6.14396727e-02 9.91876101e-07]
 [2.09907525e-07 8.56272376e-03 9.91437066e-01]
 [2.31210264e-06 2.96696185e-02 9.70328069e-01]
 [2.62266958e-07 8.10695956e-03 9.91892778e-01]
 [3.70218108e-02 9.55988438e-01 6.98975154e-03]
 [4.17215629e-07 1.04559444e-02 9.89543638e-01]
 [4.34318217e-02 9.37686101e-01 1.88820778e-02]
 [9.69929548e-07 2.09447317e-02 9.79054298e-01]
 [8.81965367e-01 1.18032114e-01 2.51906960e-06]
 [9.45925766e-01 5.40740555e-02 1.78303499e-07]
 [8.76963934e-01 1.23030024e-01 6.04189117e-06]
 [3.24381620e-07 9.66153941e-03 9.90338136e-01]
 [2.59368637e-02 9.45886635e-01 2.81765010e-02]
 [3.24987675e-02 9.47660876e-01 1.98403562e-02]
 [1.23028495e-02 9.47748937e-01 3.99482137e-02]
 [1.45795900e-07 5.74089661e-03 9.94258958e-01]
 [7.44773694e-08 4.51112624e-03 9.95488799e-01]
 [1.62962117e-06 2.72952632e-02 9.72703107e-01]
 [7.88661524e-08 4.56918794e-03 9.95430733e-01]
 [8.53527122e-06 5.73495321e-02 9.42641933e-01]
 [7.42905128e-02 9.15757563e-01 9.95192441e-03]
 [5.30946843e-07 1.36880301e-02 9.86311439e-01]
 [6.27222766e-03 8.87669607e-01 1.06058165e-01]
 [2.33519398e-07 8.52433582e-03 9.91475431e-01]
 [2.26393699e-02 9.57172224e-01 2.01884056e-02]
 [4.64752098e-02 9.43216433e-01 1.03083577e-02]
 [1.80978899e-06 2.64650121e-02 9.73533178e-01]
 [1.65879232e-06 2.37779282e-02 9.76220413e-01]
 [5.04638844e-06 4.62982528e-02 9.53696701e-01]
 [8.01446570e-01 1.98546478e-01 6.95214011e-06]
 [7.80661916e-07 1.67432932e-02 9.83255926e-01]
 [9.43048735e-02 9.04729963e-01 9.65163098e-04]
 [8.76137174e-01 1.23861546e-01 1.27905755e-06]
 [3.34017839e-06 4.74962257e-02 9.52500434e-01]
 [2.03950818e-07 7.84770829e-03 9.92152088e-01]
 [4.41151433e-07 1.00608480e-02 9.89938711e-01]
 [1.23923357e-06 2.36559955e-02 9.76342765e-01]
 [9.64404192e-01 3.55957394e-02 6.85314304e-08]
 [5.89979855e-06 4.59739004e-02 9.54020200e-01]
 [9.25731268e-08 5.10623507e-03 9.94893672e-01]
 [1.24696021e-02 9.39711862e-01 4.78185358e-02]
 [1.70692054e-06 2.61237105e-02 9.73874583e-01]
 [3.07663565e-07 1.10453186e-02 9.88954374e-01]
 [1.07723923e-06 1.69618285e-02 9.83037094e-01]
 [2.51700000e-06 2.88686509e-02 9.71128832e-01]
 [1.07058075e-06 1.88692574e-02 9.81129672e-01]
 [3.50597970e-06 4.07217537e-02 9.59274740e-01]
 [3.75262506e-02 9.42953025e-01 1.95207244e-02]
 [1.22113849e-06 1.78076662e-02 9.82191113e-01]
 [9.73380156e-01 2.66195732e-02 2.70870813e-07]
 [3.44950433e-06 3.10906095e-02 9.68905941e-01]
 [7.51001758e-07 1.58495560e-02 9.84149693e-01]
 [6.75266113e-08 4.55604708e-03 9.95443885e-01]
 [9.21933749e-01 7.80658359e-02 4.15438206e-07]
 [9.21249425e-01 7.87493282e-02 1.24716647e-06]
 [2.88690783e-02 9.46908990e-01 2.42219319e-02]
 [1.85374218e-07 7.64882677e-03 9.92350988e-01]
 [7.30246026e-07 1.51971623e-02 9.84802107e-01]
 [2.51240128e-07 8.48370302e-03 9.91516046e-01]
 [1.98621773e-02 9.54632529e-01 2.55052934e-02]
 [3.27694348e-02 9.53654338e-01 1.35762271e-02]
 [3.77158978e-07 1.09045640e-02 9.89095059e-01]
 [7.64455352e-06 6.48920985e-02 9.35100257e-01]
 [4.29750467e-06 4.20446026e-02 9.57951100e-01]
 [7.16751493e-06 5.76967078e-02 9.42296125e-01]
 [7.64581808e-01 2.35407050e-01 1.11415363e-05]
 [9.62708738e-01 3.72911794e-02 8.24556062e-08]
 [9.65213232e-01 3.47864765e-02 2.91677446e-07]
 [9.81067650e-01 1.89322513e-02 9.87004443e-08]
 [3.12802363e-07 9.71670622e-03 9.90282981e-01]
 [2.26548084e-02 9.54413574e-01 2.29316174e-02]
 [1.97922241e-06 2.79168409e-02 9.72081180e-01]
 [7.65247495e-07 1.84316508e-02 9.81567584e-01]
 [1.19706646e-06 1.79780051e-02 9.82020798e-01]
 [8.66111614e-01 1.33883701e-01 4.68530161e-06]
 [1.60076650e-06 2.09874998e-02 9.79010899e-01]
 [5.46324369e-02 9.39171738e-01 6.19582542e-03]
 [9.91633544e-07 1.73997888e-02 9.82599220e-01]
 [9.33015267e-08 5.17891209e-03 9.94820995e-01]
 [2.65025706e-07 1.01922251e-02 9.89807510e-01]
 [8.89253190e-07 1.73671595e-02 9.82631951e-01]
 [9.34938982e-01 6.50606852e-02 3.33246158e-07]
 [1.86885889e-02 9.37639556e-01 4.36718551e-02]
 [8.05499233e-07 1.60677509e-02 9.83931444e-01]
 [7.24741964e-07 1.66568343e-02 9.83342441e-01]
 [9.70201009e-01 2.97985712e-02 4.19481475e-07]
 [4.79134529e-07 1.21271927e-02 9.87872328e-01]
 [6.88530522e-02 9.24456522e-01 6.69042558e-03]
 [2.32692916e-06 2.57631468e-02 9.74234526e-01]
 [2.50565930e-02 9.49825108e-01 2.51182992e-02]
 [1.47910432e-02 9.27198067e-01 5.80108900e-02]
 [1.43313095e-06 2.23214182e-02 9.77677149e-01]
 [1.02672898e-06 2.13821338e-02 9.78616839e-01]
 [9.35175058e-01 6.48244862e-02 4.56167833e-07]
 [2.19775091e-02 9.35207212e-01 4.28152793e-02]
 [9.29032351e-01 7.09670194e-02 6.29254799e-07]
 [1.92114027e-07 6.86026877e-03 9.93139539e-01]
 [9.48580390e-01 5.14194157e-02 1.94458564e-07]
 [9.82497219e-03 9.25968249e-01 6.42067787e-02]
 [1.81674737e-02 9.55438747e-01 2.63937798e-02]
 [1.98621773e-02 9.54632529e-01 2.55052934e-02]
 [9.82994594e-01 1.70053840e-02 2.15816767e-08]
 [9.56131478e-01 4.38682917e-02 2.30244308e-07]
 [8.90378979e-01 1.09618519e-01 2.50230025e-06]
 [2.74788284e-07 8.29886699e-03 9.91700858e-01]
 [8.65601205e-07 1.63742352e-02 9.83624899e-01]
 [1.10992554e-06 2.25243595e-02 9.77474531e-01]
 [1.98723834e-06 2.76343379e-02 9.72363675e-01]
 [1.83195431e-06 2.47813761e-02 9.75216792e-01]
 [1.57707350e-06 2.10439284e-02 9.78954495e-01]
 [1.01802791e-07 5.09917607e-03 9.94900722e-01]
 [1.41746692e-06 2.00903646e-02 9.79908218e-01]
 [8.83891075e-06 6.34693634e-02 9.36521798e-01]
 [8.48274753e-03 9.12810676e-01 7.87065767e-02]
 [9.53468440e-01 4.65313111e-02 2.48382377e-07]
 [2.79405305e-07 8.99559780e-03 9.91004123e-01]]

In [ ]:
from sklearn.model_selection import cross_val_score

skor = cross_val_score(model, X,Y, cv=5,scoring='accuracy')
print("cross-validation scores: ",skor)
print("mean skor: ",skor.mean())

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

cross-validation scores:  [1. 1. 1. 1. 1.]
mean skor:  1.0

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
#evaluasi model
from sklearn.metrics import classification_report

report = classification_report(y_test,predict)
print(report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        55
           1       1.00      0.99      0.99        89
           2       1.00      1.00      1.00       151

    accuracy                           1.00       295
   macro avg       0.99      1.00      1.00       295
weighted avg       1.00      1.00      1.00       295

Implementasi model:

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

C:\Users\Acer\AppData\Local\Temp\ipykernel_10992\173348647.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train,y_train)

In [26]:
#evaluasi model
from sklearn.metrics import classification_report
print("clasification report:\n",classification_report(y_test,y_pred))

clasification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        55
           1       1.00      1.00      1.00        89
           2       1.00      1.00      1.00       151

    accuracy                           1.00       295
   macro avg       1.00      1.00      1.00       295
weighted avg       1.00      1.00      1.00       295